/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class VistaPanelAeropuerto extends javax.swing.JPanel {
    public DefaultTableModel modeloPanelAeropuerto = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
    public VistaPanelAeropuerto() {
        initComponents();
        jTablePanelAeropuerto.setModel(modeloPanelAeropuerto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAñaidrVuelo = new javax.swing.JButton();
        jButtonModificarVuelo = new javax.swing.JButton();
        jButtonEliminarVuelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePanelAeropuerto = new javax.swing.JTable();

        jButtonAñaidrVuelo.setText("Añadir Vuelo");
        jButtonAñaidrVuelo.setActionCommand("AñadirVuelo");

        jButtonModificarVuelo.setText("Modificar Vuelo");
        jButtonModificarVuelo.setActionCommand("ModificarVuelo");

        jButtonEliminarVuelo.setText("Eliminar Vuelo");
        jButtonEliminarVuelo.setActionCommand("EliminarVuelo");

        jLabel1.setText("PANEL VUELOS");

        jTablePanelAeropuerto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePanelAeropuerto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonAñaidrVuelo)
                        .addGap(150, 150, 150)
                        .addComponent(jButtonModificarVuelo)
                        .addGap(150, 150, 150)
                        .addComponent(jButtonEliminarVuelo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñaidrVuelo)
                    .addComponent(jButtonModificarVuelo)
                    .addComponent(jButtonEliminarVuelo))
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAñaidrVuelo;
    public javax.swing.JButton jButtonEliminarVuelo;
    public javax.swing.JButton jButtonModificarVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablePanelAeropuerto;
    // End of variables declaration//GEN-END:variables
}
