/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package proyectopcd;

import java.awt.Color;

/**
 *
 * @author carlo
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form ColaFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        int sizeCola = 10;

        ColaFrame frame = new ColaFrame();

        frame.setSize(800, 600);
        CanvasCola canvas = new CanvasCola(sizeCola);
        frame.add(canvas);
        frame.setVisible(true);
        ColaLenta cola = new ColaLenta(sizeCola, canvas);

        Thread productor = new Productor(cola);
        Thread productor1 = new Productor(cola);
        Thread productor2 = new Productor(cola);
        Thread productor3 = new Productor(cola);
        Consumidor c = new Consumidor(cola);
        Thread t1=new Thread(c);
                
        productor.start();
        productor1.start();
        productor2.start();
        productor3.start();
        t1.start();

        productor.join();
        productor1.join();
        productor2.join();
        productor3.join();
        t1.join();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
