/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class VistaSocios extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocios
     */
    public DefaultTableModel modeloTablaSocios = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
    public VistaSocios() {
        initComponents();
        jTableSocios.setModel(modeloTablaSocios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jButtonNuevoSocioGSocios = new javax.swing.JButton();
        jButtonActualizaSocios = new javax.swing.JButton();
        jButtonEliminaSocio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBuscaSocio = new javax.swing.JTextField();
        jButtonGestionActividades = new javax.swing.JButton();

        jLabel1.setText("GESTIÓN DE SOCIOS");

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        jButtonNuevoSocioGSocios.setText("Añadir Nuevo Socio");
        jButtonNuevoSocioGSocios.setActionCommand("AgregarSocioGSocio");
        jButtonNuevoSocioGSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoSocioGSociosActionPerformed(evt);
            }
        });

        jButtonActualizaSocios.setText("Actualizar Socio");
        jButtonActualizaSocios.setActionCommand("ActualizarSocioGSocios");
        jButtonActualizaSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizaSociosActionPerformed(evt);
            }
        });

        jButtonEliminaSocio.setText("Eliminar Socio");
        jButtonEliminaSocio.setActionCommand("EliminarSocio");

        jLabel2.setText("Nombre");

        jLabel3.setText("BUSCA SOCIO");

        jTextFieldBuscaSocio.setToolTipText("");
        jTextFieldBuscaSocio.setActionCommand("BuscaSocio");
        jTextFieldBuscaSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaSocioKeyReleased(evt);
            }
        });

        jButtonGestionActividades.setText("Gestionar Acitidades");
        jButtonGestionActividades.setActionCommand("GestionarAcitidades");
        jButtonGestionActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionActividadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonNuevoSocioGSocios)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonActualizaSocios)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonEliminaSocio)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonGestionActividades))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldBuscaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBuscaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoSocioGSocios)
                    .addComponent(jButtonEliminaSocio)
                    .addComponent(jButtonActualizaSocios)
                    .addComponent(jButtonGestionActividades))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizaSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizaSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizaSociosActionPerformed

    private void jButtonNuevoSocioGSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoSocioGSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoSocioGSociosActionPerformed

    private void jTextFieldBuscaSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaSocioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaSocioKeyReleased

    private void jButtonGestionActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionActividadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizaSocios;
    public javax.swing.JButton jButtonEliminaSocio;
    public javax.swing.JButton jButtonGestionActividades;
    public javax.swing.JButton jButtonNuevoSocioGSocios;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocios;
    public javax.swing.JTextField jTextFieldBuscaSocio;
    // End of variables declaration//GEN-END:variables
}
