/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class VistaMonitor extends javax.swing.JPanel {

    /**
     * Creates new form VistaMonitor
     */
    public DefaultTableModel modeloTablaMonitores = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
    public VistaMonitor() {
        initComponents();
        jTableMonitores.setModel(modeloTablaMonitores);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();
        jButtonEliminarMonitor = new javax.swing.JButton();
        jButtonActualización = new javax.swing.JButton();
        jButtonAgregarMonitor = new javax.swing.JButton();

        jLabel1.setText("GESTIÓN DE MONITORES");

        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitores);

        jButtonEliminarMonitor.setText("Eliminar monitor");
        jButtonEliminarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMonitorActionPerformed(evt);
            }
        });

        jButtonActualización.setText("Actualización de monitor");
        jButtonActualización.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizaciónActionPerformed(evt);
            }
        });

        jButtonAgregarMonitor.setText("Agregar monitor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonAgregarMonitor)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonActualización)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonEliminarMonitor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarMonitor)
                    .addComponent(jButtonEliminarMonitor)
                    .addComponent(jButtonActualización))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizaciónActionPerformed

    private void jButtonEliminarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualización;
    public javax.swing.JButton jButtonAgregarMonitor;
    public javax.swing.JButton jButtonEliminarMonitor;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitores;
    // End of variables declaration//GEN-END:variables
}
