/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author carlo
 */
public class VistaGestionActividades extends javax.swing.JDialog {

    /**
     * Creates new form VistaGestionActividades
     */
    public VistaGestionActividades() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDarDeAltaUnSocioDeUnaActividad = new javax.swing.JMenuItem();
        jMenuItemDarDeBajaUnSocioDeUnaActividad = new javax.swing.JMenuItem();
        SalirGActividades = new javax.swing.JMenu();
        jMenuItemSalirGActividades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("Gestión Actividades");
        jMenu1.setActionCommand("jMenu");

        jMenuItemDarDeAltaUnSocioDeUnaActividad.setText("DarDeAltaUnSocioDeUnaActividad");
        jMenu1.add(jMenuItemDarDeAltaUnSocioDeUnaActividad);

        jMenuItemDarDeBajaUnSocioDeUnaActividad.setText("DarDeBajaUnSocioDeUnaActividad");
        jMenuItemDarDeBajaUnSocioDeUnaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDarDeBajaUnSocioDeUnaActividadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDarDeBajaUnSocioDeUnaActividad);

        jMenuBar1.add(jMenu1);

        SalirGActividades.setText("Salir");

        jMenuItemSalirGActividades.setText("Salir");
        jMenuItemSalirGActividades.setActionCommand("SalirGActividades");
        jMenuItemSalirGActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirGActividadesActionPerformed(evt);
            }
        });
        SalirGActividades.add(jMenuItemSalirGActividades);

        jMenuBar1.add(SalirGActividades);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDarDeBajaUnSocioDeUnaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDarDeBajaUnSocioDeUnaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDarDeBajaUnSocioDeUnaActividadActionPerformed

    private void jMenuItemSalirGActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirGActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirGActividadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SalirGActividades;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemDarDeAltaUnSocioDeUnaActividad;
    public javax.swing.JMenuItem jMenuItemDarDeBajaUnSocioDeUnaActividad;
    public javax.swing.JMenuItem jMenuItemSalirGActividades;
    // End of variables declaration//GEN-END:variables
}
