/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMonitores = new javax.swing.JMenu();
        jMenuItemMonitores = new javax.swing.JMenuItem();
        jMenuItemCuotaMonitor = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuItemSocios = new javax.swing.JMenuItem();
        jMenuActividades = new javax.swing.JMenu();
        jMenuItemCuantosSocios = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuSalirLogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuMonitores.setText("Monitores");

        jMenuItemMonitores.setText("Gestión de Monitores");
        jMenuItemMonitores.setActionCommand("GestionMonitores");
        jMenuMonitores.add(jMenuItemMonitores);

        jMenuItemCuotaMonitor.setText("Cuota de Monitor");
        jMenuItemCuotaMonitor.setActionCommand("CuotadeMonitor");
        jMenuMonitores.add(jMenuItemCuotaMonitor);

        jMenuBar1.add(jMenuMonitores);

        jMenuSocios.setText("Socios");

        jMenuItemSocios.setText("Gestión de Socios");
        jMenuSocios.add(jMenuItemSocios);

        jMenuBar1.add(jMenuSocios);

        jMenuActividades.setText("Actividades");

        jMenuItemCuantosSocios.setText("Actividades");
        jMenuItemCuantosSocios.setActionCommand("CuantosSocios");
        jMenuActividades.add(jMenuItemCuantosSocios);

        jMenuBar1.add(jMenuActividades);

        jMenuSalir.setText("Salir");
        jMenuSalir.setActionCommand("SalirLogin");

        jMenuItemSalir.setText("Salir de la aplicación");
        jMenuSalir.add(jMenuItemSalir);

        jMenuSalirLogin.setText("Salir al login");
        jMenuSalirLogin.setActionCommand("SalirLogin");
        jMenuSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirLoginActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuSalirLogin);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalirLoginActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenuActividades;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemCuantosSocios;
    public javax.swing.JMenuItem jMenuItemCuotaMonitor;
    public javax.swing.JMenuItem jMenuItemMonitores;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenuItem jMenuItemSocios;
    public javax.swing.JMenu jMenuMonitores;
    public javax.swing.JMenu jMenuSalir;
    public javax.swing.JMenuItem jMenuSalirLogin;
    public javax.swing.JMenu jMenuSocios;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}
